import requests
import os
import json
import time
import hashlib

from sawtooth_sdk.processor.handler import TransactionHandler
from sawtooth_sdk.processor.exceptions import InvalidTransaction
from sawtooth_sdk.processor.exceptions import InternalError

IOC_NAMESPACE = hashlib.sha512('ioc'.encode("utf-8")).hexdigest()[0:6]
CAPE_UPLOAD_URL = "http://localhost:8000/apiv2/tasks/create/file/"
CAPE_STATUS_URL = "http://localhost:8000/apiv2/tasks/status/{0}/"
CAPE_REPORT_URL = "http://localhost:8000/apiv2/tasks/get/report/json/"


def make_address(addr):
	return IOC_NAMESPACE + addr

def compare_reports(user_report,cape_report):

	n_files_u = user_report[""]

class IocTransactionHandler(TransactionHandler):

	@property
	def family_name(self):
		return 'ioc'

	@property
	def family_versions(self):
		return ['1.0']

	@property
	def namespaces(self):
		return [IOC_NAMESPACE]

	def apply(self, transaction, context):
		
		payload = transaction.payload()
		
		#Get the file hash to retrieve the complete program from the tmp folder
		user_report = json.loads(payload)
		file_name = user_report["SHA512"][:64]
		addr = make_address(file_name)
		state_dict = context.get_state([addr])

		# Check whether the incoming behavioural report is a root one of just an 
		# addition over a previous one

		#ADDITION
		if len(state_dict) > 0:
			context.set_state({addr:\
				state_dict[addr]+ "," + transaction.header_signature})

		# ROOT BEHAVIOURAL REPORT
		else:
		
			if not os.path.exists("/tmp/" + file_name):
				raise InvalidTransaction("File not uploaded to the server")

			#Generate a CAPE task with the executable
			files = {'upload_file': open('/tmp/' + file_name,'rb')}
			r = requests.post(CAPE_UPLOAD_URL, files=files)

			if r.status_code != 200:
				raise InvalidTransaction("Unable to generate CAPE task")

			task_id = json.loads(r.text)["data"]["task_ids"]

			#POLL the CAPE API to track execution of the task
			while(True):
				r = requests.get(CAPE_STATUS_URL.format(task_id))
				if r.status_code != 200:
					raise InvalidTransaction("Error while polling CAPE task")
				status = json.loads(r.text)["data"]
				if status == "analyzed" or status == "reported":
					break
				elif status == "processing":
					time.sleep(15)
				else:
					raise InvalidTransaction("CAPE processing error")

			#Check the report generated by CAPE
			r = requests.get(CAPE_REPORT_URL)
			if r.status_code != 200:
				raise InvalidTransaction("Error retrieving the report")
			cape_report = json.loads(r.text)
			res = compare_reports(user_report,cape_report)

			#Update the global state if the transaction is valid
			if res:
				context.set_state({addr : transaction.header_signature})


