# Generated by Django 3.2.3 on 2021-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=200)),
                ('report_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('batch_id', models.CharField(max_length=130)),
            ],
        ),
    ]
