# Generated by Django 3.2.3 on 2021-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
